# Generated by Django 5.0.4 on 2024-05-04 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='Номер стола')),
                ('description', models.CharField(max_length=200, unique=True)),
                ('maxGuests', models.IntegerField(verbose_name='Макс количество человек')),
                ('guestsDef', models.IntegerField(blank=True, null=True, verbose_name='Гостей')),
                ('guestsNow', models.IntegerField(blank=True, null=True, verbose_name='Присутствует гостей')),
            ],
            options={
                'verbose_name': 'Столы',
                'verbose_name_plural': 'Столы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='ФИО')),
                ('isPresent', models.BooleanField(default=True, verbose_name='Присутствие')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kafe.tables', verbose_name='Столы')),
            ],
            options={
                'verbose_name': 'Гости',
                'verbose_name_plural': 'Гости',
                'ordering': ('name', 'created'),
                'index_together': {('id',)},
            },
        ),
    ]
