# Generated by Django 5.0.4 on 2024-05-04 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafe', '0002_alter_tables_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guests',
            name='isPresent',
            field=models.BooleanField(default=False, verbose_name='Присутствие'),
        ),
        migrations.AlterField(
            model_name='guests',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kafe.tables', verbose_name='Столы'),
        ),
        migrations.AlterField(
            model_name='tables',
            name='guestsNow',
            field=models.BooleanField(default=False, verbose_name='Присутствует гостей'),
        ),
    ]
