# Generated by Django 5.0.4 on 2024-05-04 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafe', '0003_alter_guests_ispresent_alter_guests_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guests',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kafe.tables', verbose_name='Столы'),
        ),
    ]
