# Generated by Django 5.0.4 on 2024-05-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafe', '0004_alter_guests_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tables',
            name='guestsNow',
            field=models.IntegerField(default=0, verbose_name='Присутствует гостей'),
        ),
    ]
