# Generated by Django 5.0.4 on 2024-05-04 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafe', '0005_alter_tables_guestsnow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guests',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kafe.tables', verbose_name='Столы'),
        ),
        migrations.AlterField(
            model_name='tables',
            name='guestsDef',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Гостей'),
        ),
    ]
