# Generated by Django 5.0.4 on 2024-05-05 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafe', '0007_alter_guests_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guests',
            options={'ordering': ('name', 'created'), 'verbose_name': 'Гость', 'verbose_name_plural': 'Гости'},
        ),
        migrations.AlterModelOptions(
            name='tables',
            options={'ordering': ['id'], 'verbose_name': 'Стол', 'verbose_name_plural': 'Столы'},
        ),
        migrations.AlterField(
            model_name='guests',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kafe.tables', verbose_name='Стол'),
        ),
    ]
